
MODEL_TRAINER_DIR = "model_trainer"
MODEL_TRAINER_TRAINED_MODEL_DIR = "saved_models"
MODEL_TRAINER_MODEL_NAME = "fin_complaint_est.pth"
MODEL_TRAINER_EPOCH = 1
MODEL_TRAINER_BATCH_SIZE = 2048
MODEL_TRAINER_DATASET_SPLIT_RATIO=0.2
MODEL_TRAINER_PARENT_CACHE_DIR_URL_CONF = "cache_dir"
